function GUIgamma()

global h prefs;
load_vars();

%% Gamma Figure
h.gamma = figure(...
    'Name','Channel Layout',...
    'units','pixels',...
    'Color', prefs.BackColor,...
    'NumberTitle','off',...
    'MenuBar', 'none',...
    'Toolbar', 'none',...
    'Resize','off',...
    'units','pixels',...
    'Position', [prefs.UIs,prefs.UIs,prefs.UIs * 4.5 + prefs.cbW * 1, prefs.UIs * 7.5 + prefs.cbH * 4]);

prefs.WS = get(0, 'ScreenSize'); % h.gamma, 'Position'

%% Gamma UI panels
h.gamma.uigamma = uipanel(...
    h.gamma,...
    'Tag', 'controlPanel1',...
    'Title', 'Cols',...
    'BackgroundColor',prefs.BackColor,...
    'ForegroundColor', prefs.ForeColor,...
    'Clipping', 'on',...
    'Units','pixels',...
    'Position',[prefs.UIs,prefs.UIs,prefs.WS(1,3:4)-(2.5*prefs.UIs)]);



%% Gamma Labels and Textboxes
for i = 1:4
h.gamma.lbl{i} = uicontrol(...
    h.gamma,...
    'Tag', ['lbl',num2str(i)],...
    'Style', 'text',...
    'String', ['Gamma ', num2str(i)],...
    'Callback', @cbnLoad);
end
movegui(h.chlayout, 'center');


end