
function h = saveTraces(tr)
% dialog to get measurement parameters

h = figure(...
    'Name','Save Traces',...
    'Units','normalized',...
    'NumberTitle','off',...
    'MenuBar', 'none',...
    'Toolbar', 'none',...
    'Resize','off',...
    'OuterPosition', [0.4,0.2,0.3,0.3]);

save_options = uipanel('Parent',h, ...
    'Title','Save',...
    'Position',[0.1,.45,.4,.5]);

op_raw = uicontrol(...
    save_options,...
    'Style', 'text',...
    'HorizontalAlignment','left',...
    'String', 'Raw',...
    'units', 'normalized',...
    'Position', [.1,.5,.75,.3]);

op_raw_box = uicontrol(...
    save_options,...
    'Value',1,...
    'Style', 'checkbox',...
    'units', 'normalized',...
    'Position', [.8,.5,.15,.3]);

op_steps = uicontrol(...
    save_options,...
    'Style', 'text',...
    'HorizontalAlignment','left',...
    'String', 'Steps',...
    'units', 'normalized',...
    'Position', [.1,.2,.75,.3]);

op_steps_box = uicontrol(...
    save_options,...
    'Style', 'checkbox',...
    'Value',0,...
    'units', 'normalized',...
    'Position', [.8,.2,.15,.3]);
% 
% op_numfit = uicontrol(...
%     save_options,...
%     'Style', 'text',...
%     'HorizontalAlignment','left',...
%     'String', 'Num fit',...
%     'units', 'normalized',...
%     'Position', [.1,.2,.75,.2]);
% 
% op_numfit_box = uicontrol(...
%     save_options,...
%     'Style', 'checkbox',...
%     'units', 'normalized',...
%     'Position', [.8,.2,.15,.2]);

% ----------------------------------------
% Buttons

save_button = uicontrol(...
    h,...
    'Style', 'pushbutton',...
    'String','Save',...
    'units', 'normalized',...
    'Position', [.6,.7,.3,.2]);

browse_button = uicontrol(...
    h,...
    'Style', 'pushbutton',...
    'String','Browse folder...',...
    'units', 'normalized',...
    'Position', [.6,.45,.3,.2]);


% ----------------------------------------
% Text

folder_name = uicontrol(...
    h,...
    'Style', 'text',...
    'HorizontalAlignment','left',...
    'String',pwd,...
    'units', 'normalized',...
    'Position', [.1,.25,.8,.15]);

file_txt = uicontrol(...
    h,...
    'Style', 'text',...
    'HorizontalAlignment','left',...
    'String','File name: ',...
    'units', 'normalized',...
    'Position', [.1,.05,.8,.15]);

file_name = uicontrol(...
    h,...
    'Style', 'edit',...
    'HorizontalAlignment','left',...
    'String','variable_save',...
    'units', 'normalized',...
    'Position', [.25,.1,.6,.15]);

% CALLBACKS

save_button.Callback = {@save_btn,op_raw_box,op_steps_box,folder_name,file_name,tr};
browse_button.Callback = {@browse,folder_name};

end


function save_btn(~,~,op_raw_box,op_steps_box,folder_name,file_name,tr)
    
    sz1 = size(tr,2);
    sz2 = size(tr{1},2);
    
    raw_op = get(op_raw_box,'Value');
    step_op = get(op_steps_box,'Value');
    folder = get(folder_name,'String');
    file = get(file_name,'String');
    
    
    
    % define variables
    Raw = zeros(sz1,sz2);
    Step = zeros(sz1,sz2);
    
    if raw_op
        for i = 1:sz1
            Raw(i,:) = tr{i};
        end
    end

    if step_op
        for i = 1:sz1
            Step(i,:) = stepfit1_alvaro(tr{i});
        end 
    end

    
    if raw_op && ~step_op
        save(strcat(folder,'\',file),'Raw');
    elseif ~raw_op && step_op
        save(strcat(folder,'\',file),'Step');
    else
        save(strcat(folder,'\',file),'Raw','Step');
    end
end


function browse(~,~,folder_name)
    folder = uigetdir;
    folder_name.String = folder;
end

