function imgBrowserGUI()
%IMAGEBROWSER Summary of this function goes here
%   Detailed explanation goes here
h.imgbrowser = figure(...
    'Name', 'TRACER: Data Loading Window',...
    'NumberTitle','off',...
    'units', 'normalized', ...
    'OuterPosition', [0,0,1,1],...
    'GraphicsSmoothing', 'on',...
    'MenuBar', 'none',...
    'KeyPressFcn', [],...
    'Toolbar', 'none',...
    'WindowKeyPressFcn', [],...
    'WindowButtonMotionFcn',[]);


h.imgbrowser_pan_tree = uipanel(h.imgbrowser,'Title','Folder','Position',[0,0,0.3,1]);


h.imgbrowser_pan_file = uipanel(h.imgbrowser,'Title','File','Position',[.3,0,0.4,1]);

h.imgbrowser_pan_cam = uipanel(h.imgbrowser,'Title', 'Camera Config', 'Position',[.7,0,0.3,1]);

end

